### PR TITLE
Made a simple site in Rust and fixed pr template

### PR DESCRIPTION
**Pull request by ghost**
Mark X to agree:
- I have made sure my code is inline with the [code guidelines](https://docs.avdanos.com/docs/category/code-guidelines) [x]
- I have updated all readme files that need to be updated [x]

### CODE REVIEW

**Comment by ghost** [comment]
Sorry for this mess but i'm really fussy, so i just wanted to have the readme file concise and perfect

**Review by MrSerge01 — APPROVED** [review]
so pro even I can't do it

LGTM,
-The Goos.

**Review by StoneMcYT — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Coolness

**Review by Froxcey — APPROVED** [review]
LGTM

vibe

**Pull request merged**
