### PR TITLE
Added data types file

### PR DESCRIPTION
**Pull request by TechStudent10**
Mark X to agree:
- I have made sure my code is inline with the [code guidelines](https://docs.avdanos.com/docs/category/code-guidelines)? [X]
- I have updated all readme files that need to be updated [X]

This was made while watching a video on Rust data types.

### CODE REVIEW

**Comment by lucasod3v** [comment]
Maybe update README.md to have info about this file...

**Comment by TechStudent10** [comment]
hm okay

**Comment by ghost** [comment]
I don't see the reason of this

**Comment by TechStudent10** [comment]
> I don't see the reason of this

Well I mean this is for Rust experiments and I thought that adding a data types file could serve as a kind of reference material for Rust data types.

**Comment by lucasod3v** [comment]
> > I don't see the reason of this
> 
> 
> 
> Well I mean this is for Rust experiments and I thought that adding a data types file could serve as a kind of reference material for Rust data types.

Yeah, this could be a little useful when I don't want to dive into millions of pages with documentation.

**Review by ghost — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
no wait nvm have to fix conflicts

**Pull request merged**
